services:
  tntnet:
    build: ./
    ports:
      - "8080:8080"  # TNTnet listens on 8080
    depends_on:
      - php-fpm
    networks:
      - app-network
    environment:
      - PHP_FPM_HOST=php-fpm
      - PHP_FPM_PORT=9000
    volumes:
      - ./php-app:/app/php:ro  # Mount PHP files for TNTnet to access

  php-fpm:
    image: php:8.1-fpm
    ports:
      - "9000:9000"  # PHP-FPM listens on 9000
    volumes:
      - ./php-app:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
